[workspace]
members = [
    "apps/cargo-link2",
    "crates/dudy-malloc",
    "crates/is-macro",
    "crates/hstr",
    "crates/default-from-serde",
    "crates/st-map",
]
resolver = "2"


[workspace.package]
edition    = "2021"
license    = "Apache-2.0"
repository = "https://github.com/dudykr/ddbase.git"

[workspace.dependencies]
Inflector             = { version = "0.11.4", default-features = false }
arrayvec              = "0.7.2"
compact_str           = "0.7.1"
criterion             = "0.5.1"
hashbrown             = { version = "0.14.3", default-features = false }
kstring               = "2.0.0"
new_debug_unreachable = "1.0.4"
num_cpus              = "1.16.0"
once_cell             = "1.18.0"
phf                   = "0.11.2"
proc-macro2           = "1.0.70"
quote                 = "1.0.33"
rand                  = "0.8.5"
rayon                 = "1.8.0"
rkyv                  = "0.7.42"
rustc-hash            = "1.1.0"
serde                 = { version = "1.0.192", default-features = false }
serde_derive          = "1.0.193"
smartstring           = "1.0.1"
smol_str              = "0.2.0"
string_cache          = "0.8.7"
syn                   = "2.0.39"
triomphe              = "0.1.11"
