[workspace]
members = [
    "apps/cargo-link2",
    "crates/dudy-malloc",
    "crates/is-macro",
    "crates/hstr",
    "crates/default-from-serde",
    "crates/st-map",
]
resolver = "2"


[workspace.package]
edition    = "2021"
license    = "Apache-2.0"
repository = "https://github.com/dudykr/ddbase.git"
