[workspace]
members = [
    "crates/dudy-malloc",
    "crates/hstr",
    "crates/default-from-serde",
    "xtask",
]
resolver = "2"


    [workspace.dependencies]
    derive-default-from-serde = { path = "./crates/derive-default-from-serde" }
