[package]
edition.workspace    = true
license.workspace    = true
name                 = "shrink-to-fit"
repository.workspace = true
version              = "0.1.0"

[dependencies]
hashbrown = { workspace = true, optional = true }
indexmap  = { workspace = true, optional = true }

[features]
hashbrown = ["dep:hashbrown"]
indexmap  = ["dep:indexmap"]
